services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DATABASE_URL=pgsql://symfony:symfony@db:5432/symfony
    networks:
      - symfony

  web:
    image: nginx:alpine
    container_name: symfony_web
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony

  pgadmin:
    image: dpage/pgadmin4
    container_name: symfony_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: abdessamad.bannouf@laposte.net
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_db_password
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - symfony
    secrets:
      - pgadmin_db_password
volumes:
  pgdata:
  pgadmin_data:

networks:
  symfony:

secrets:
  db_password:
    file: ./db/db_password.txt
  pgadmin_db_password:
    file: ./db/pgadmin_db_password.txt